### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by akashnimare** [trulia/webpagetest-charts-ui#3]
I am getting this error
Unexpected token u

undefined

SyntaxError: Unexpected token u
    at Object.parse (native)
    at Request._callback (/home/akash/webpagetest-charts-ui/routes/home.js:13:17)
    at self.callback (/home/akash/webpagetest-charts-ui/node_modules/request/request.js:121:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at Request.self._buildRequest (/home/akash/webpagetest-charts-ui/node_modules/request/request.js:336:39)
    at Request.init (/home/akash/webpagetest-charts-ui/node_modules/request/request.js:503:10)
    at new Request (/home/akash/webpagetest-charts-ui/node_modules/request/request.js:97:8)
    at request (/home/akash/webpagetest-charts-ui/node_modules/request/index.js:50:11)
    at Object.module.exports [as handle] (/home/akash/webpagetest-charts-ui/routes/home.js:11:3)
    at next_layer (/home/akash/webpagetest-charts-ui/node_modules/express/lib/router/route.js:103:13)

My WPT api is up and running.

**Comment by bigethan** [comment]
it seems like it's not looking in the right place for your API?  the value there should be json (`rawJson`) but if that is undefined, that's where the `u` error is coming from.  If you put a 

```javascript 
console.log(process.env.WPT_API + '/suite_config');
```
on line 10 of `routes/home.js` does it show a URL that works properly?

**Comment by akashnimare** [comment]
I don't know where I am getting wrong. Here is the process I did
For Setting up webpagetest-charts-api
1. Clone webpagetest-charts-api
2. npm install
3. Created a config.json file (Added WPT KEY)
4. SUITE_CONFIG=config.json npm start
I can see the tests running on localhost:3001 (Though I was unable to see the charts)

For UI
1. Clone webpagetest-charts-api 
2. npm install
3. WPT_API="localhost:3001" npm start
When I run above command I see nothing except this
 > node ./bin/www

**Comment by akashnimare** [comment]
Thanks I have figured out the problem. It's working now.

**Comment by akashnimare** [comment]
It would be very good If we can add the date range in the options instead of days shown. So that It will add date ranges in the X axis.

**Comment by bigethan** [comment]
It's certainly possible - we've never had a need for it though.  PRs are welcome :-)
